#
# Copyright (c) 2017 Paul Borza
#
# This software may be modified and distributed under the terms
# of the MIT license. See the LICENSE file for details.
#
    
# https://www.cyberpowersystems.com/product/software/powerpanel-for-linux/
- name: install cyberpower shutdown software
  become: true
  apt:
    deb: https://dl4jz3rbrsfum.cloudfront.net/software/powerpanel_132_amd64.deb
